### ISSUE TITLE
"deceased" field not updating?

### ISSUE THREAD

**Issue by airadam** [katacek/covid-uk#6]
I can see with calls to the endpoint for latest stats over a few days that while the `lastUpdatedAtApify` and `lastUpdatedAtSource` fields are being updated, as well as the daily stats like `dailyDeceasedWithin28Days`, the `deceased` field appears to be static - it hasn't moved from 95829 since Friday. Is this intentional (and something I'm misunderstanding), or a bug?

**Comment by katacek** [comment]
The number of `deceased ` is taken from here: [https://coronavirus.data.gov.uk/details/deaths](url).
As the number is `95 829` at the moment, it seems that it has not been updated at the source since 20/01/2020.
If you find more accurate data, just let me know, I can rewrite the scaper.
Thank you!

**Comment by airadam** [comment]
Ah, I see there are two separate figures there - the one I'm seeing is for "Deaths with COVID-19 on the death certificate" which is actually described as having a lag, and then there's a separate, higher figure for "Deaths within 28 days of positive test" which may or may not have been changing. Your comment makes total sense - thank you, and thanks for writing the scraper/endpoint in the first place!
